services:
  postgres:
    image: postgres:17
    container_name: SEC
    restart: always
    environment:
      POSTGRES_DB: message
      POSTGRES_USER: gd
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: